defaults: &defaults
  admin_username: admin
  admin_password: password
  admin_email: admin@example.com
  atos_username: atos
  atos_password: password
  atos_secondary_username: atos2
  atos_secondary_password: password
local:
  <<: *defaults
  et1_url: http://et1.et.127.0.0.1.nip.io:3100/
  diversity_url: http://et1.et.127.0.0.1.nip.io:3100/apply/diversity
  et1_admin_url: http://et1.et.127.0.0.1.nip.io:3100/apply/admin
  et3_url: http://et3.et.127.0.0.1.nip.io:3100/
  atos_api_url: http://atos.et.127.0.0.1.nip.io:3100
  admin_url: http://admin.et.127.0.0.1.nip.io:3100/admin
  sidekiq_url: http://et1.et.127.0.0.1.nip.io:3100/apply/sidekiq
  mailhog_search_url: http://mail.et.127.0.0.1.nip.io:3100/api/v2/search
production:
  <<: *defaults
  # et1_url: https://www.employmenttribunals.service.gov.uk/
  # et1_url: https://staging1.et.dsd.io/
  # diversity_url: https://www.employmenttribunals.service.gov.uk/apply/diversity
  # et1_admin_url: https://www.employmenttribunals.service.gov.uk/apply/admin
  # et3_url: https://tribunal-response.employmenttribunals.service.gov.uk/
  # atos_api_url: https://atos-api.employmenttribunals.service.gov.uk
  # admin_url: https://admin.employmenttribunals.service.gov.uk/admin
  # api_url: https://et-atos-api-dev-azure.dev.et.dsd.io
dev: 
  <<: *defaults
  et1_url: https://et-dev-azure.dev.et.dsd.io
  diversity_url: https://et-dev-azure.dev.et.dsd.io/en/apply/diversity
  et3_url: https://et3-dev-azure.dev.et.dsd.io
  admin_url: https://et-admin-dev-azure.dev.et.dsd.io/admin
  api_url: https://et-api-dev-azure.dev.et.dsd.io
  atos_api_url: https://et-atos-api-dev-azure.dev.et.dsd.io
  sidekiq_url: https://et-dev-azure.dev.et.dsd.io/apply/sidekiq
staging: 
  <<: *defaults
  et1_url: https://et-stg-azure.staging.et.dsd.io
  diversity_url: https://et-stg-azure.staging.et.dsd.io/en/apply/diversity
  et3_url: https://et3-stg-azure.staging.et.dsd.io
  admin_url: https://et-admin-stg-azure.staging.et.dsd.io/admin
  api_url: https://et-api-stg-azure.staging.et.dsd.io
  atos_api_url: https://et-atos-api-stg-azure.staging.et.dsd.io
  sidekiq_url: https://et-stg-azure.staging.et.dsd.io/apply/sidekiq
  atos_username: atos
  atos_password: password
  atos_secondary_username: atos2
  atos_secondary_password: password
