defaults: &defaults
  admin_username: admin@example.com
  admin_password: password
local: 
  <<: *defaults
  et1_url: http://et1.et.127.0.0.1.nip.io:3100/
  et3_url: http://et3.et.127.0.0.1.nip.io:3100/
  atos_api_url: http://api.et.127.0.0.1.nip.io:3100/atos_api
  admin_url: http://admin.et.127.0.0.1.nip.io:3100/admin
  aws_endpoint_url: http://s3.et.127.0.0.1.nip.io:3100/
dev:
  <<: *defaults
  et1_url: https://dev1.et.dsd.io/
  et3_url: https://et3-dev.et.dsd.io/
  atos_api_url: https://api-dev.et.dsd.io/atos_api
  admin_url: https://admin-dev.et.dsd.io/admin
  aws_endpoint_url: http://s3.et.127.0.0.1.nip.io:3100/
staging:
  <<: *defaults
  et1_url: https://staging1.et.dsd.io/
  et3_url: https://et3-staging.et.dsd.io/
  atos_api_url: https://api-staging.et.dsd.io/atos_api
  admin_url: https://admin-staging.et.dsd.io/admin
  aws_endpoint_url: http://s3.et.127.0.0.1.nip.io:3100/
# production:
#   <<: *defaults
#   et1_url: https://www.employmenttribunals.service.gov.uk/
#   et3_url: https://tribunal-response.employmenttribunals.service.gov.uk/
#   atos_api_url: https://api.tribunal-response.employmenttribunals.service.gov.uk/atos_api
#   admin_url: https://admin.tribunal-response.employmenttribunals.service.gov.uk/admin
#   aws_endpoint_url: http://s3.et.127.0.0.1.nip.io:3100/